apiVersion: v1
kind: Service
metadata:
  name: devops-learning
  namespace: devops-learning
  labels:
    app: devops-learning
spec:
  selector:
    app: devops-learning
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: NodePort